language: node_js
script: "npm run travis"
node_js:
  - node
  - "7"
  - "8"
  - "9"
addons:
  chrome: stable
services:
  - xvfb
before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
